Create Table User(
USER_ID  NUMBER(10,0) NOT NULL AUTO_INCREMENT,
FIRST_NAME VARCHAR2(250), 
LAST_NAME VARCHAR2(250),
ADDRESS1 VARCHAR2(250),
ADDRESS2 VARCHAR2(250),
CITY VARCHAR2(250),
STATE VARCHAR2(2),
ZIP VARCHAR2(9),
COUNTRY VARCHAR2(2),
CREATED_DATE timestamp,
PRIMARY KEY (USER_ID)
);

CREATE SEQUENCE USER_ID_SEQ
  MINVALUE 1
  MAXVALUE 9999999999999999
  START WITH 1
  INCREMENT BY 100
  CACHE 100;
  
  INSERT INTO USER(FIRST_NAME, 
LAST_NAME,
ADDRESS1,
ADDRESS2,
CITY,
STATE,
ZIP,
COUNTRY,
CREATED_DATE)
VALUES('Nicholas','Brown', 'Test', 'Test', 'Farmington', 'MI', '48188', 'US', CURRENT_TIME());

INSERT INTO USER(FIRST_NAME, 
LAST_NAME,
ADDRESS1,
ADDRESS2,
CITY,
STATE,
ZIP,
COUNTRY,
CREATED_DATE)
VALUES('Jane','Doe', 'Test', 'Test', 'Farmington', 'MI', '48188', 'US', CURRENT_TIME())